### ISSUE TITLE
[Core Concept] CPI

### ISSUE THREAD

**Issue by jacobcreech** [solana-developers/solana-cookbook#166]
We need a section explaining CPI on Solana and the current limits

For example:
- Currently limited to a depth of 4
- How is CPI done?
- How is it done within the validator?
- Invoke vs invoke_signed

**Comment by ZYJLiu** [comment]
![cpi_4](https://user-images.githubusercontent.com/75003086/160232455-c46f26d1-7720-4d6a-9c0e-ee831106eb58.png)
![cpi_1](https://user-images.githubusercontent.com/75003086/160232456-658bb254-9375-41e6-a921-03d9ce69fcf0.png)
![cpi_2](https://user-images.githubusercontent.com/75003086/160232457-0d3a83d8-0f2e-42a7-887a-99ef6c5c5022.png)
![cpi_3](https://user-images.githubusercontent.com/75003086/160232458-dba06673-6b9a-41d4-8b93-9fadaeb15123.png)

**Comment by ZYJLiu** [comment]
[cpi.md](https://github.com/solana-developers/solana-cookbook/files/8355040/cpi.md)

**Comment by ZYJLiu** [comment]
![cpi_1](https://user-images.githubusercontent.com/75003086/160232541-7cef97fe-499c-46ff-860a-5887b622235f.png)
![cpi_2](https://user-images.githubusercontent.com/75003086/160232542-370e0d35-3e9b-4673-bee2-79b7294255b5.png)
![cpi_3](https://user-images.githubusercontent.com/75003086/160232543-96211b0d-3356-4603-a432-9d40d9e22151.png)
![cpi_4](https://user-images.githubusercontent.com/75003086/160232545-77b96a81-ebb9-41de-a8ea-f349a63e70f7.png)

**Comment by jacobcreech** [comment]
> [cpi.md](https://github.com/solana-developers/solana-cookbook/files/8355040/cpi.md)

Could you make a PR?

**Comment by ZYJLiu** [comment]
https://github.com/solana-developers/solana-cookbook/pull/515
