### ISSUE TITLE
[Code] Update Code Preview

### ISSUE THREAD

**Issue by jacobcreech** [solana-developers/solana-cookbook#176]
People are having trouble with code previews and getting confused on full source vs the preview

Let's add some default information displayed in a different color such as `Press </> button to view full source` at the top of every source

**Comment by ehteshaxm** [comment]
Can I work on this?

**Comment by jacobcreech** [comment]
@ehteshaxm Go right ahead!

**Comment by jacobcreech** [comment]
@0xPratik Assigned! Go ahead and start :)

**Comment by 0xPratik** [comment]
Hey @jacobcreech i have started working on this issue and i have a small question that i would like to get your suggestions on it. Thanks

In this Image the text is outside the code section and if we want it to look this way than have to make changes on all the code snippets. I looked for a DRY way to write it out but there isn't much code to understand the internal working of it.
<img width="859" alt="Screenshot 2022-03-02 at 10 59 48 PM" src="https://user-images.githubusercontent.com/62953475/156415887-10a3e112-3d9f-4683-a480-2a8461e9cff8.png">

This is another way that I tried out here I have included some code in the SolanaCodeGroupItem.vue component. Which shows the message in the code snippet. What do you think is a better approach.
<img width="884" alt="Screenshot 2022-03-02 at 10 57 52 PM" src="https://user-images.githubusercontent.com/62953475/156417151-8a1bcd01-0510-4ac6-b79b-9a52d234d17f.png">

**Comment by jacobcreech** [comment]
@0xPratik Love the second way, where the message is at the top of the component, not above it. Updating the vue component is the way to go

**Comment by 0xPratik** [comment]
Got it @jacobcreech Creating the Pull request in a few minutes for it. Thanks for the quick response you are awsome.
