### ISSUE TITLE
Chapter on Anchor is confusing 

### ISSUE THREAD

**Issue by CSDUMMI** [solana-developers/solana-cookbook#238]
The chapter on Anchor is very confusingly phrased.

Specifically:

> # Accounts Deserializers
> A struct deriving all the accounts used by an instruction. The program can't read other accounts after. Here is possible to define if an account is initialized or modified by the instruction, if an account is using a PDA, and execute accounts validation.

[Anchor Chapter](https://solanacookbook.com/references/anchor.html#accounts-deserializers)

**Comment by jacobcreech** [comment]
@CSDUMMI Hmm, makes sense. Will see what we can do on updating this

**Comment by migui3230** [comment]
@jacobcreech Let me take this  on!

**Comment by migui3230** [comment]
#324 @jacobcreech
