### ISSUE TITLE
[Snippet] Send a token to the payer as part of a transaction

### ISSUE THREAD

**Issue by mcintyre94** [solana-developers/solana-cookbook#293]
This came up on the Solana discord: https://discord.com/channels/428295358100013066/517163444747894795/953743912437166150

The transaction should:

- Have Alice send Bob some SOL
- Have Bob send Alice an SPL token
- Be partially signed by Bob, so that only Alice needs to sign it after it's returned to her

There didn't seem to be any documentation for this that anyone could point to, so I think it'd be useful to add to the cookbook

I have a minimal NextJS example here: https://github.com/mcintyre94/solana-partially-signed - and would like to contribute a variant of it

**Comment by jacobcreech** [comment]
There is a version of it here https://solanacookbook.com/references/offline-transactions.html#sign-transaction

Maybe it isn't discoverable enough. The instructions are a bit unclear too given the common question. Happy to accept suggestions and additional examples

**Comment by jacobcreech** [comment]
Closing with #294
