### ISSUE TITLE
account size units

### ISSUE THREAD

**Issue by php4fan** [solana-developers/solana-cookbook#327]
https://solanacookbook.com/core-concepts/accounts.html#facts

> Accounts have a max size of 10mb
> PDA accounts have a max size of 10kb

I can tell that the max size of an account is certainly not 10 **millibits**, but I wonder whether it is supposed to be Mb (megabits) or MB (megabytes). I bet it's MB.

And that makes me suspect the size of PDA accounts is probably 10 kB as well, isn't it?

**Comment by 0xdeepmehta** [comment]
Its byte (megabyte, kilobyte)

**Comment by 0xdeepmehta** [comment]
tho a good point, PRs are welcome :)

**Comment by d3fkon** [comment]
Made a PR, this misinfo was off-putting while going through the cookbook
