### ISSUE TITLE
Update Token reference page with new SPL-Token

### ISSUE THREAD

**Issue by Jac0xb** [solana-developers/solana-cookbook#333]
Never commited to the Solana Cookbook but I couldn't help but notice that the references are to an older version of the spl-token ts package and was wondering if this is something that I could contribute towards update?

**Comment by jacobcreech** [comment]
@Jac0xb When you say an older version, what do you mean? They should be of the latest version

**Comment by Jac0xb** [comment]
Ahh looks like the typescript types are wrong in the latest spl-token distribution <.<
