### ISSUE TITLE
[Integration] Switchboard Oracle

### ISSUE THREAD

**Issue by gallynaut** [solana-developers/solana-cookbook#365]
Switchboard is a native Solana oracle used by most of the major Solana DeFi platforms. An integration guide would be useful for new projects looking to consume data on-chain.

**Comment by anoushk1234** [comment]
hey @gallynaut @jacobcreech can take this one up, already familiar with switchboard

**Comment by jacobcreech** [comment]
@anoushk1234 Assigned!

**Comment by anoushk1234** [comment]
hey @gallynaut made a draft pr #372 let me know if there's something else to be added apart from this. I do plan to add documentation on adding jobs to aggregators examples too

**Comment by anoushk1234** [comment]
@jacobcreech @gallynaut check it out #372
