### ISSUE TITLE
Usage of deprecated metaplex javascript SDK

### ISSUE THREAD

**Issue by mukesh272921** [solana-developers/solana-cookbook#385]
Most of the snippets in the NFT reference section uses the deprecated metaplex package (i.e `@metaplex/js`, metaplex has a new javascript SDK -- [`@metaplex-foundation/js`](https://github.com/metaplex-foundation/js)).

Here are the links of the snippets which uses the deprecated metaplex javascript SDK:
- https://solanacookbook.com/references/nfts.html#mint-the-nft
- https://solanacookbook.com/references/nfts.html#how-to-get-nft-metadata
- https://solanacookbook.com/references/nfts.html#how-to-get-all-nfts-from-a-wallet

I would like to change the code of these snippets to use the new metaplex javascript SDK

**Comment by jacobcreech** [comment]
@mukesh272921 Please do! Would love to get the updates
