### ISSUE TITLE
Full dApp for Staking SPL Tokens

### ISSUE THREAD

**Issue by jainkrati** [solana-developers/solana-cookbook#420]
Hi! I have a Rust program for staking spl tokens and the frontend code which interacts with it. I would like to add it to Solana cookbook, under "Solana by example" kind of section, so that no one faces the "[Cross-program invocation with unauthorized signer or writable account](https://solana.stackexchange.com/questions/1492/cross-program-invocation-with-unauthorized-signer-or-writable-account)" issue which I was facing. 

Raising this as a issue for better guidance.

**Comment by jacobcreech** [comment]
This is a full tutorial/guide? We run full program examples in https://github.com/solana-developers/program-examples, not cookbook

**Comment by jainkrati** [comment]
Yes it is a guide to create Rust program for staking spl tokens. Thanks for clarifying. I will try to add it in program-examples.
