### ISSUE TITLE
Transferências 

### ISSUE THREAD

**Issue by Washingtonnas** [solana-developers/solana-cookbook#471]
Olá me chamo washington Lopes venho respeitosamente em forma que meu torkens não foram creditado pelo app fone minerador paguei para minerar e depois sacar meus lucros infelizmente não obtive exedo com as minhas transferências preciso de um retorno onde foram parar meu ativos atenciosamente aguardando o retorno do mesmo boa tarde

**Comment by Rinkie77** [comment]
Hope we get help here.

Web3 is the best
