### ISSUE TITLE
Metaplex JS SDK Candy Machine examples

### ISSUE THREAD

**Issue by 0xMukesh** [solana-developers/solana-cookbook#473]
Hey! Metaplex JS SDK now supports creating Candy Machine v2 via code in [v0.17.0](https://github.com/metaplex-foundation/js/releases/tag/js%2Fv0.17.0). I would like to add code examples regarding the Candy Machine module under the[ NFTs reference section](https://solanacookbook.com/references/nfts.html)

**Comment by jacobcreech** [comment]
Go for it!
