### ISSUE TITLE
Replace Serum documentation with OpenBook 

### ISSUE THREAD

**Issue by beeman** [solana-developers/solana-cookbook#577]
The [Serum Integration](https://solanacookbook.com/integrations/serum.html) on the Cookbook should be replaced with OpenBook.

OpenBook is the community-led fork of the Serum V3 program that's been in use since last year and should be recommended over Serum.

If a developer that's new to the ecosystem comes across this documentation they will use the wrong program which is not great.

**Comment by coolestnick** [comment]
Hi, Can I work on this issue? Please assign me!

**Comment by shifu-brighton** [comment]
> Hi, Can I work on this issue? Please assign me!

I don't think you need permission, just fork the project and try your best. If your pr gets approved well then good for you.

**Comment by coolestnick** [comment]
Can I get the openBook documentation link to integrate it?

**Comment by web3contri** [comment]
hey! @beeman please checkout #594, this issue has been solved in the pull request mentioned

**Comment by aych-dev** [comment]
Looking into this now...

**Comment by beeman** [comment]
This issue is no longer available for Gib Work.

Please don't start working on it, you will not receive the bounty.
